apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
stringData:
  MYSQL_ROOT_PASSWORD: "wp_root"
  MYSQL_DATABASE: "wp_dbname"
  MYSQL_USER: "wp_user"
  MYSQL_PASSWORD: "wp_passwd"
  WORDPRESS_DB_HOST: "db:3306"
  WORDPRESS_DB_USER: "wp_user"
  WORDPRESS_DB_PASSWORD: "wp_passwd"
  WORDPRESS_DB_NAME: "wp_dbname"
