services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - type: volume
        source: mysql_vol
        target: /db:/var/lib/mysql
    networks:
      wp_network:
        ipv4_address: 172.20.0.2

  web:
    build: .
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content/
    networks:
      wp_network:
        ipv4_address: 172.20.0.3

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      wp_network:
        ipv4_address: 172.20.0.4

networks:
  default:
    name: bridge
  wp_network:
    name: wp_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  mysql_vol:
